In [20]:
import pandas as pd
import random
import numpy as np

df = pd.read_csv('house.sale.0805.csv')
df.head()

ID                                     Location   Region      District  \
0  115611                       Kotayk, Qasakh, Qasakh   Kotayk        Qasakh   
1  115609        Yerevan, Nor Norq, Bagrevand district  Yerevan      Nor Norq   
2  115596                     Yerevan, Avan, Avan 5 St  Yerevan          Avan   
3  115593  Yerevan, Norq Marash, Armenak Armenakyan St  Yerevan   Norq Marash   
4  115587               Yerevan, Avan, Paruyr Sevak 11  Yerevan          Avan   

                   Street    Price  Price/sqm   Views  Area  Room  ...  \
0                  Qasakh    92000        153   774.0   600     4  ...   
1      Bagrevand district   330000        471  1370.0   700     5  ...   
2               Avan 5 St   130000        260  1125.0   500     4  ...   
3   Armenak Armenakyan St  1700000       1133  1173.0  1500     7  ...   
4         Paruyr Sevak 11   350000        583   928.0   600     4  ...   

        Condition  Date Added Date Edited  Date Scraped   Latitude  Longitude  \
0  Newly repaired  25.10.2021  25.10.2021    08.05.2022  40.235526  44.451442   
1  Newly repaired  25.10.2021  25.10.2021    08.05.2022  40.192484  44.586332   
2  Newly repaired  25.10.2021  25.10.2021    08.05.2022  40.147115  44.516820   
3  Newly repaired  24.10.2021  24.10.2021    08.05.2022  40.189037  44.530844   
4  Newly repaired  24.10.2021  24.10.2021    08.05.2022  40.228469  44.579354   

                                             Address  \
0  9, Վազգեն Սարգսյանի փողոց, Քասախ, Եղվարդի տարա...   
1          Բագրևանդ, Նոր Նորք, Ջրվեժ, 0089, Հայաստան   
2  Կենտրոնական զինվորական հիվանդանոց, Նոր Արեշի 5...   
3  73, Արմենակ Արմենակյան փողոց, Նորք Մարաշ, Երևա...   
4  29, Պարույր Սևակ թաղ 1-ին փողոց, Առինջ, Աբովյա...   

                                          Facilities  \
0  ['Heating', 'Hot water', 'Electricity', 'Gas',...   
1  ['Heating', 'Hot water', 'Electricity', 'Gas',...   
2  ['Heating', 'Internet', 'Hot water', 'Electric...   
3  ['Heating', 'Internet', 'Electricity', 'Air-co...   
4  ['Heating', 'Internet', 'Hot water', 'Electric...   

                                     Additional Info  \
0  ['Euro windows', 'Tile', 'Sunny', 'View', 'Park']   
1  ['Furniture', 'Equipment', 'Euro windows', 'Ir...   
2  ['Furniture', 'Equipment', 'Euro windows', 'Ir...   
3  ['Furniture', 'Equipment', 'Fireplace', 'Euro ...   
4  ['Open balcony', 'Attic', 'Sunny', 'View', 'Ga...   

                                                 url  
0  https://myrealty.am/en/house-for-sale/Qasakh/Q...  
1  https://myrealty.am/en/house-for-sale/Bagrevan...  
2  https://myrealty.am/en/house-for-sale/Avan+5+S...  
3  https://myrealty.am/en/house-for-sale/Armenak+...  
4  https://myrealty.am/en/house-for-sale/Paruyr+S...  

[5 rows x 24 columns]

In [2]:
df.Price.unique()

array([  92000,  330000,  130000, 1700000,  350000,  266000,   68000,
         95000,  225000,  150000,  550000,  112000,  650000,   28000,
        165000,  800000,  420000,  120000,  300000,  133000,  500000,
        400000,  250000,   90000,  200000,  520000,  270000,   50000,
        320000,  230000,  154000,   87000, 1050000,   80000,  153000,
        360000,   70000,   75000,  125000,  490000,   85000,  260000,
        100000,  450000,  148000,  135000,  170000,   53000,  127000,
         62000,  480000, 1600000,  140000,  680000,  750000, 1300000,
        160000, 2000000,  590000,  600000,  155000, 1800000,  145000,
        220000,  259900,  370000,  168000,  440000,  380000,  109000,
       1500000, 1075000,  475000, 2400000,   73000,  460000,   33000,
        110000,  430000,  700000,   58000,  195000,   77000,  105000,
        245000,  113000,  385000,  180000,   63000,  122000,  190000,
        185000,   72000,  850000,   82000,   44000,  123000,  390000,
        128000,  451

In [21]:
df.rename(columns = {'Storeys':'Floors'}, inplace = True)
df['on_request'] = 0
df['Error'] = 0
df['Floor'] = np.nan
df['Storeys'] = np.nan
df['Listing_type'] = 'for sale'
df['Property_type'] = 'house'
df['Platform_name'] = pd.Series(random.choices(['myrealty.am','bars.am'],
                                                     weights=[1, 1], k=len(df)))
df.head()

ID                                     Location   Region      District  \
0  115611                       Kotayk, Qasakh, Qasakh   Kotayk        Qasakh   
1  115609        Yerevan, Nor Norq, Bagrevand district  Yerevan      Nor Norq   
2  115596                     Yerevan, Avan, Avan 5 St  Yerevan          Avan   
3  115593  Yerevan, Norq Marash, Armenak Armenakyan St  Yerevan   Norq Marash   
4  115587               Yerevan, Avan, Paruyr Sevak 11  Yerevan          Avan   

                   Street    Price  Price/sqm   Views  Area  Room  ...  \
0                  Qasakh    92000        153   774.0   600     4  ...   
1      Bagrevand district   330000        471  1370.0   700     5  ...   
2               Avan 5 St   130000        260  1125.0   500     4  ...   
3   Armenak Armenakyan St  1700000       1133  1173.0  1500     7  ...   
4         Paruyr Sevak 11   350000        583   928.0   600     4  ...   

                                          Facilities  \
0  ['Heating', 'Hot water', 'Electricity', 'Gas',...   
1  ['Heating', 'Hot water', 'Electricity', 'Gas',...   
2  ['Heating', 'Internet', 'Hot water', 'Electric...   
3  ['Heating', 'Internet', 'Electricity', 'Air-co...   
4  ['Heating', 'Internet', 'Hot water', 'Electric...   

                                     Additional Info  \
0  ['Euro windows', 'Tile', 'Sunny', 'View', 'Park']   
1  ['Furniture', 'Equipment', 'Euro windows', 'Ir...   
2  ['Furniture', 'Equipment', 'Euro windows', 'Ir...   
3  ['Furniture', 'Equipment', 'Fireplace', 'Euro ...   
4  ['Open balcony', 'Attic', 'Sunny', 'View', 'Ga...   

                                                 url  on_request Error Floor  \
0  https://myrealty.am/en/house-for-sale/Qasakh/Q...           0     0   NaN   
1  https://myrealty.am/en/house-for-sale/Bagrevan...           0     0   NaN   
2  https://myrealty.am/en/house-for-sale/Avan+5+S...           0     0   NaN   
3  https://myrealty.am/en/house-for-sale/Armenak+...           0     0   NaN   
4  https://myrealty.am/en/house-for-sale/Paruyr+S...           0     0   NaN   

  Storeys Listing_type  Property_type  Platform_name  
0     NaN     for sale          house        bars.am  
1     NaN     for sale          house        bars.am  
2     NaN     for sale          house        bars.am  
3     NaN     for sale          house        bars.am  
4     NaN     for sale          house    myrealty.am  

[5 rows x 31 columns]

In [4]:
df.Price.describe()

count    1.500000e+03
mean     3.068617e+05
std      2.965985e+05
min      8.000000e+03
25%      1.300000e+05
50%      2.200000e+05
75%      3.800000e+05
max      2.941176e+06
Name: Price, dtype: float64

In [5]:
df.Area.unique()

array([  600,   700,   500,  1500,   400,   200,   250,   280,   450,
        1300,   440,  1000,   860,   820,   800,    96,   120,   630,
         750,   215,   357,  3460,  1200,   512,   260,  7000,  1100,
         300,   620,   760,   850,   374,   826,  3000,  3700,  1400,
         780,   350,   180,   150,   245,   550,   345,   146,  1977,
        3162,   756,   680,   377,  1050,   244,   590,  1040,  1600,
         210,   235,   772,   370,   273,    80,   726,  1030,   265,
        1950,   185,   240,  1150,   387,   720,   270,   530,  1700,
         197,   580,   584,   650,   460,   520,   930,   390,   320,
         135,   640,  2200,   470,   454,   480,  3350,  4435,   572,
         510,   137,   163,  2000,   675,    70,    60,   420,   446,
         170,   444,    90,   625,   110,   168,  1240,   100,   333,
         681,   960,   220,  6000,   225,   310,   298,  1520,    86,
         900,   475,   360,   980,  5800,   410,   457,  1678,   230,
         129,   118,

In [6]:
df.Area.quantile(0.01)

50.0

In [22]:
df.loc[df['Area'] < 50 , 'Error'] = 1

In [8]:
df.Views.describe()

count     1498.000000
mean      3425.764352
std       2875.516847
min         70.000000
25%       1353.250000
50%       2654.500000
75%       4684.000000
max      45902.000000
Name: Views, dtype: float64

In [9]:
df.Room.unique()

array([4, 5, 7, 6, 1, 3, 2])

In [10]:
df.Storeys.unique()

array([1, 3, 2, 4, 5, 0, 6])

In [23]:
df.loc[df.Storeys == 0 , 'Error'] = 1

In [12]:
df.Bathrooms.unique()

array([1, 3, 5, 2, 4])

In [13]:
df.BuildType.unique()

array(['Stone', 'Monolit', 'Other', 'Panel'], dtype=object)

In [14]:
df.CeilingHeight.unique()

array([2.8, 3. , 3.2, 3.8, 2.6, 5. ])

In [15]:
df.Condition.unique()

array(['Newly repaired', 'Good', 'Zero condition'], dtype=object)

In [16]:
df.Latitude.describe()

count    1500.000000
mean       40.204344
std         1.278401
min        18.338096
25%        40.183333
50%        40.193996
75%        40.216387
max        53.726668
Name: Latitude, dtype: float64

In [24]:
df.loc[df.Latitude < 38 , 'Error'] = 1
df.loc[df.Longitude < 40 , 'Error'] = 1

In [25]:
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace("]", ""))
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace("[", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace("]", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace("[", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace("'", ""))
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace("'", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace(" ", ""))
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace(" ", ""))
df1 = pd.DataFrame(df['Facilities'].str.get_dummies(sep=','))
df2 = pd.DataFrame(df['Additional Info'].str.get_dummies(sep=','))
info = pd.concat([df1, df2], axis=1)
house_sale = pd.concat([df, info], axis=1)
house_sale.head()

ID                                     Location   Region      District  \
0  115611                       Kotayk, Qasakh, Qasakh   Kotayk        Qasakh   
1  115609        Yerevan, Nor Norq, Bagrevand district  Yerevan      Nor Norq   
2  115596                     Yerevan, Avan, Avan 5 St  Yerevan          Avan   
3  115593  Yerevan, Norq Marash, Armenak Armenakyan St  Yerevan   Norq Marash   
4  115587               Yerevan, Avan, Paruyr Sevak 11  Yerevan          Avan   

                   Street    Price  Price/sqm   Views  Area  Room  ...  \
0                  Qasakh    92000        153   774.0   600     4  ...   
1      Bagrevand district   330000        471  1370.0   700     5  ...   
2               Avan 5 St   130000        260  1125.0   500     4  ...   
3   Armenak Armenakyan St  1700000       1133  1173.0  1500     7  ...   
4         Paruyr Sevak 11   350000        583   928.0   600     4  ...   

   Parquet  Playground Roadside  Sauna Securitysystem Storageroom Sunny  \
0        0           0        0      0              0           0     1   
1        1           0        0      0              1           0     1   
2        1           0        1      0              1           1     1   
3        0           0        0      1              1           0     1   
4        0           0        0      0              0           0     1   

  Swimmingpool  Tile  View  
0            0     1     1  
1            0     1     1  
2            0     1     0  
3            1     1     1  
4            0     0     1  

[5 rows x 78 columns]

In [19]:
house_sale.columns

Index(['ID', 'Location', 'Region', 'District', 'Street', 'Price', 'Price/sqm',
       'Views', 'Area', 'Room', 'Storeys', 'Bathrooms', 'BuildType',
       'CeilingHeight', 'Condition', 'Date Added', 'Date Edited',
       'Date Scraped', 'Latitude', 'Longitude', 'Address', 'Facilities',
       'Additional Info', 'url', 'on_request', 'Error', 'Air-conditioner',
       'Canalization', 'Centralheating', 'Electricity', 'Gas', 'Heating',
       'Hotwater', 'Internet', 'Irrigation', 'Sewerage', 'Water', 'water24/7',
       'Attic', 'Balcony', 'Basement', 'Bilateral', 'Buildingexistence',
       'Closetothebusstation', 'Elevator', 'Equipment', 'Eurowindows', 'Fence',
       'Fireplace', 'Furniture', 'Garage', 'Gate', 'Grating', 'Gym',
       'Heatedfloor', 'Heater', 'Highfirstfloor', 'Irondoor',
       'Laminateflooring', 'Loggia', 'Openbalcony', 'Park', 'Parking',
       'Parquet', 'Playground', 'Roadside', 'Sauna', 'Securitysystem',
       'Storageroom', 'Sunny', 'Swimmingpool', 'Tile', 'Vie

In [26]:
house_sale.to_csv('house_sale_filtered.csv', index = False)