In [28]:
import pandas as pd
import numpy as np
import random

df = pd.read_csv('house.rent.0805.csv')
df.head()

ID                           Location   Region  District  \
0  121413          Tavush, Dilijan, Dilidjan   Tavush   Dilijan   
1  121226      Yerevan, Center, Kajaznuni St  Yerevan    Center   
2  121050       Yerevan, Erebuni, Suvorov st  Yerevan   Erebuni   
3  121014   Yerevan, Arabkir, Ghapantsian St  Yerevan   Arabkir   
4  120996  Yerevan, Arabkir, Shrjancik Tunel  Yerevan   Arabkir   

             Street Price  Views  Area  Room  Storeys  ...       Condition  \
0          Dilidjan  4500    122  1000     6        2  ...            Good   
1      Kajaznuni St  4500    196   385     7        3  ...  Newly repaired   
2        Suvorov st  3000    310   325     6        3  ...  Newly repaired   
3    Ghapantsian St  4000    331   580     6        2  ...  Newly repaired   
4   Shrjancik Tunel  4800    346  1000     4        2  ...  Newly repaired   

   Date Added  Date Edited Date Scraped   Latitude  Longitude  \
0  04.05.2022   04.05.2022   08.05.2022  40.740552  44.862597   
1  28.04.2022   28.04.2022   08.05.2022  40.166373  44.521132   
2  20.04.2022   20.04.2022   08.05.2022  40.154135  44.515477   
3  19.04.2022   19.04.2022   08.05.2022  40.295531  44.358808   
4  18.04.2022   18.04.2022   08.05.2022  40.233466  44.538971   

                                             Address  \
0  9, Կալինինի փողոց, Դիլիջան, Դիլիջանի տարածաշրջ...   
1        20, Քաջազնունի փողոց, Երևան, 0070, Հայաստան   
2  42, Սուվորովի փողոց, Էրեբունի, Երևան, 0008, Հա...   
3  29, Գրիգոր Ղափանցյան փոզոց, Աշտարակ, Աշտարակի ...   
4  25/4, Շրջանցիկ Թունել փողոց, Արաբկիր, Երևան, 0...   

                                          Facilities  \
0  ['Water', 'water 24/7', 'Electricity', 'Intern...   
1  ['Water', 'water 24/7', 'Electricity', 'Air-co...   
2  ['Heating', 'Internet', 'Hot water', 'Electric...   
3  ['Heating', 'Internet', 'Hot water', 'Electric...   
4  ['Water', 'water 24/7', 'Electricity', 'Air-co...   

                                     Additional Info  \
0  ['Playground', 'Park', 'Roadside', 'Close to t...   
1  ['Iron door', 'Roadside', 'Close to the bus st...   
2  ['Furniture', 'Equipment', 'Euro windows', 'Ti...   
3  ['Furniture', 'Equipment', 'Euro windows', 'Op...   
4  ['Playground', 'Park', 'Roadside', 'Close to t...   

                                                 url  
0  https://myrealty.am/en/house-for-rent/Dilidjan...  
1  https://myrealty.am/en/house-for-rent/Kajaznun...  
2  https://myrealty.am/en/new-build-house-for-ren...  
3  https://myrealty.am/en/new-build-house-for-ren...  
4  https://myrealty.am/en/house-for-rent/Shrjanci...  

[5 rows x 23 columns]

In [29]:
df.rename(columns = {'Storeys':'Floors'}, inplace = True)

In [33]:
df['on_request'] = np.where(df['Price']== 'on request', 1, 0)
df.loc[df['Price'] == 'on request','Price'] = np.nan
df['Price/sqm'] = np.nan
df['Error'] = 0
df['Floor'] = np.nan
df['Storeys'] = np.nan
df['Listing_type'] = 'for rent'
df['Property_type'] = 'house'
df['Platform_name'] = pd.Series(random.choices(['myrealty.am','bars.am'],
                                                     weights=[1, 1], k=len(df)))
df.head()

ID                           Location   Region  District  \
0  121413          Tavush, Dilijan, Dilidjan   Tavush   Dilijan   
1  121226      Yerevan, Center, Kajaznuni St  Yerevan    Center   
2  121050       Yerevan, Erebuni, Suvorov st  Yerevan   Erebuni   
3  121014   Yerevan, Arabkir, Ghapantsian St  Yerevan   Arabkir   
4  120996  Yerevan, Arabkir, Shrjancik Tunel  Yerevan   Arabkir   

             Street Price  Views  Area  Room  Floors  ...  \
0          Dilidjan  4500    122  1000     6       2  ...   
1      Kajaznuni St  4500    196   385     7       3  ...   
2        Suvorov st  3000    310   325     6       3  ...   
3    Ghapantsian St  4000    331   580     6       2  ...   
4   Shrjancik Tunel  4800    346  1000     4       2  ...   

                                     Additional Info  \
0  ['Playground', 'Park', 'Roadside', 'Close to t...   
1  ['Iron door', 'Roadside', 'Close to the bus st...   
2  ['Furniture', 'Equipment', 'Euro windows', 'Ti...   
3  ['Furniture', 'Equipment', 'Euro windows', 'Op...   
4  ['Playground', 'Park', 'Roadside', 'Close to t...   

                                                 url  on_request Price/sqm  \
0  https://myrealty.am/en/house-for-rent/Dilidjan...           0       NaN   
1  https://myrealty.am/en/house-for-rent/Kajaznun...           0       NaN   
2  https://myrealty.am/en/new-build-house-for-ren...           0       NaN   
3  https://myrealty.am/en/new-build-house-for-ren...           0       NaN   
4  https://myrealty.am/en/house-for-rent/Shrjanci...           0       NaN   

  Error Floor Storeys  Listing_type  Property_type Platform_name  
0     0   NaN     NaN      for rent          house   myrealty.am  
1     0   NaN     NaN      for rent          house       bars.am  
2     0   NaN     NaN      for rent          house       bars.am  
3     0   NaN     NaN      for rent          house   myrealty.am  
4     0   NaN     NaN      for rent          house       bars.am  

[5 rows x 31 columns]

In [3]:
df.Price.unique()

array(['4500', '3000', '4000', '4800', '2500', '2000', '6000', '5000',
       '710', '1000', '1700', '700', '406', '750', '6500', '1500', '1100',
       '1900', '4200', '3700', '3500', '438', '2200', '8000', '1200',
       '285', '1400', '1800', '1600', '1300', '900', '10000', '7000',
       '480000', '800', '500', '600', '850', '2700', '2300', '309',
       '1262', '2850', nan, '210', '2400', '2800', '460', '340', '450',
       '5500', '1550', '520', '842', '526', '113', '2350', '7500', '9000',
       '2900', '11', '2600', '600000', '200', '300', '350', '550', '1350',
       '2290', '2390', '182', '400', '914', '3100', '2104', '1650',
       '4900', '3200', '3800', '530', '381', '248', '1473', '316', '3300',
       '631', '12000', '1788'], dtype=object)

In [34]:
df['Price'] = df['Price'].apply(lambda x: float(x))

In [5]:
df.Price.quantile(0.99)

10000.0

In [35]:
df.loc[df['Price'] > 10000 , 'Error'] = 1

In [7]:
df.Area.unique()

array([1000,  385,  325,  580,  500,  800,  400, 1400, 1150,  501,  220,
        300,  700,  265,  150,  600,  232,  200,  960,  550,  270, 1500,
        660, 1030, 1492,  120, 1600,  250,  288, 1450, 1020,  100,  380,
        716, 1200,   52, 1580,  350, 1100,  330,  680,  850,  650,  164,
         70,  630, 2000, 2513,  230,   82,  278,  387,  506,  180,  750,
        130,  780, 1035, 1054,   80,  450,   98,  360,  260,  160, 2500,
        182,  492,  320,  110,  950,   50,  384,  166, 1800,  145,  430,
        980,   45,   90,  710, 3162,  210,   40,   10,    1,  880, 2055,
         30, 1080, 1120,  240,  770,  102,  266,  125,  940,  170,  310,
        705, 5100,  406, 1650,  245, 3000,  915,  190,   96,  370,  470,
       1300, 1537, 6300,  620,  378,   60,  253,  178,   51,  140,  185,
        720,  314,  340,  622,  840,  216,  144,  137, 2300, 2560, 1077,
       4000,  900, 1700,   65, 1260,  534,  863,  530,   20,  475,   58,
        806, 3500,  197,  760,   95,  507,  425,  4

In [8]:
df.Area.quantile(0.01)

50.0

In [36]:
df.loc[df['Area'] <= 40 , 'Error'] = 1

In [10]:
df.Views.describe()

count      690.000000
mean      4048.662319
std       2456.745887
min        122.000000
25%       2011.250000
50%       3868.500000
75%       5813.500000
max      13739.000000
Name: Views, dtype: float64

In [11]:
df.Room.unique()

array([6, 7, 4, 5, 3, 2, 1])

In [12]:
df.Storeys.unique()

array([ 2,  3,  4,  1,  8,  5, 24])

In [37]:
df.loc[df.Storeys == 24 , 'Error'] = 1

In [14]:
df.Bathrooms.unique()

array([4, 3, 2, 5, 1])

In [15]:
df.BuildType.unique()

array(['Other', 'Stone', 'Monolit'], dtype=object)

In [16]:
df.CeilingHeight.unique()

array([2.8, 3.2, 3. , 3.8, 5. ])

In [17]:
df.Condition.unique()

array(['Good', 'Newly repaired', 'Zero condition'], dtype=object)

In [18]:
df.Latitude.describe()

count    690.000000
mean      40.196703
std        0.629787
min       36.114322
25%       40.183333
50%       40.195686
75%       40.214850
max       53.726668
Name: Latitude, dtype: float64

In [38]:
df.loc[df.Latitude < 38 , 'Error'] = 1

In [20]:
df.Longitude.describe()

count    690.000000
mean      42.863327
std       15.324128
min     -127.647621
25%       44.487231
50%       44.510843
75%       44.532364
max       46.406795
Name: Longitude, dtype: float64

In [39]:
df.loc[df.Longitude < 40 , 'Error'] = 1

In [40]:
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace("]", ""))
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace("[", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace("]", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace("[", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace("'", ""))
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace("'", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace(" ", ""))
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace(" ", ""))
df1 = pd.DataFrame(df['Facilities'].str.get_dummies(sep=','))
df2 = pd.DataFrame(df['Additional Info'].str.get_dummies(sep=','))
info = pd.concat([df1, df2], axis=1)
house_rent = pd.concat([df, info], axis=1)
house_rent.head()

ID                           Location   Region  District  \
0  121413          Tavush, Dilijan, Dilidjan   Tavush   Dilijan   
1  121226      Yerevan, Center, Kajaznuni St  Yerevan    Center   
2  121050       Yerevan, Erebuni, Suvorov st  Yerevan   Erebuni   
3  121014   Yerevan, Arabkir, Ghapantsian St  Yerevan   Arabkir   
4  120996  Yerevan, Arabkir, Shrjancik Tunel  Yerevan   Arabkir   

             Street   Price  Views  Area  Room  Floors  ...  Parquet  \
0          Dilidjan  4500.0    122  1000     6       2  ...        0   
1      Kajaznuni St  4500.0    196   385     7       3  ...        1   
2        Suvorov st  3000.0    310   325     6       3  ...        0   
3    Ghapantsian St  4000.0    331   580     6       2  ...        0   
4   Shrjancik Tunel  4800.0    346  1000     4       2  ...        0   

  Playground  Roadside Sauna Securitysystem Storageroom Sunny  Swimmingpool  \
0          1         1     0              0           0     1             0   
1          0         1     0              0           0     1             0   
2          1         1     0              0           0     1             0   
3          1         1     0              1           0     1             0   
4          1         1     0              0           0     1             0   

   Tile View  
0     1    1  
1     0    1  
2     1    1  
3     1    1  
4     1    1  

[5 rows x 78 columns]

In [23]:
house_rent.columns

Index(['ID', 'Location', 'Region', 'District', 'Street', 'Price', 'Views',
       'Area', 'Room', 'Storeys', 'Bathrooms', 'BuildType', 'CeilingHeight',
       'Condition', 'Date Added', 'Date Edited', 'Date Scraped', 'Latitude',
       'Longitude', 'Address', 'Facilities', 'Additional Info', 'url',
       'on_request', 'Price/sqm', 'Error', 'Air-conditioner', 'Canalization',
       'Centralheating', 'Electricity', 'Gas', 'Heating', 'Hotwater',
       'Internet', 'Irrigation', 'Sewerage', 'Water', 'water24/7', 'Attic',
       'Balcony', 'Basement', 'Bilateral', 'Buildingexistence',
       'Closetothebusstation', 'Elevator', 'Equipment', 'Eurowindows', 'Fence',
       'Fireplace', 'Furniture', 'Garage', 'Gate', 'Grating', 'Gym',
       'Heatedfloor', 'Heater', 'Highfirstfloor', 'Irondoor',
       'Laminateflooring', 'Loggia', 'Openbalcony', 'Park', 'Parking',
       'Parquet', 'Playground', 'Roadside', 'Sauna', 'Securitysystem',
       'Storageroom', 'Sunny', 'Swimmingpool', 'Tile', 'Vie

In [41]:
house_rent.to_csv('house_rent_filtered.csv', index=False)