In [27]:
import pandas as pd
import numpy as np
import random

df = pd.read_csv('apt.rent.0805.csv')
df.head()

ID                                  Location   Region  District  \
0  84218                Yerevan, Center, Saryan St  Yerevan    Center   
1  84217           Yerevan, Center, Sayat-Nova Ave  Yerevan    Center   
2  84181               Yerevan, Center, Amiryan St  Yerevan    Center   
3  84177           Yerevan, Center, Sayat-Nova Ave  Yerevan    Center   
4  84167  Yerevan, Arabkir, Baghramyan av(Arabkir)  Yerevan   Arabkir   

                    Street Price   Views  Area  Room  Floor  ...  \
0                Saryan St   600  2929.0    75     2      9  ...   
1           Sayat-Nova Ave   950  3036.0   103     3      7  ...   
2               Amiryan St   890  2694.0    75     3      9  ...   
3           Sayat-Nova Ave   950  2653.0   103     3      7  ...   
4   Baghramyan av(Arabkir)  1300  3009.0   120     3      4  ...   

        Condition  Date Added Date Edited  Date Scraped   Latitude  Longitude  \
0            Good  10.09.2019  14.12.2019    08.05.2022  40.182390  44.505119   
1  Newly repaired  10.09.2019  06.05.2020    08.05.2022  40.182126  44.512085   
2  Newly repaired  10.09.2019  14.12.2019    08.05.2022  40.180622  44.508178   
3  Newly repaired  10.09.2019  14.12.2019    08.05.2022  40.183568  44.520496   
4  Newly repaired  10.09.2019  09.07.2020    08.05.2022  40.193848  44.497105   

                                             Address  \
0  27, Սարյանի փողոց, Կենտրոն, Երևան, 0002, Հայաստան   
1  30, Եզնիկ Կողբացու փողոց, Կենտրոն, Երևան, 0002...   
2  HAF-HAF, 13/45, Ամիրյան փողոց, Կենտրոն, Երևան,...   
3  21, Սայաթ-Նովայի պողոտա, Կենտրոն, Երևան, 0001,...   
4  59, Մարշալ Բաղրամյան պողոտա, Արաբկիր, Երևան, 0...   

                                          Facilities  \
0  ['Heating', 'Internet', 'Hot water', 'Electric...   
1  ['Heating', 'Internet', 'Hot water', 'Sewerage...   
2  ['Heating', 'Internet', 'Hot water', 'Electric...   
3  ['Heating', 'Internet', 'Hot water', 'Electric...   
4  ['Heating', 'Internet', 'Hot water', 'Sewerage...   

                                     Additional Info  \
0  ['Furniture', 'Equipment', 'Euro windows', 'Ti...   
1  ['Furniture', 'Equipment', 'Euro windows', 'Ir...   
2  ['Furniture', 'Equipment', 'Euro windows', 'Ti...   
3  ['Furniture', 'Equipment', 'Euro windows', 'Ti...   
4  ['Furniture', 'Equipment', 'Euro windows', 'Ir...   

                                                 url  
0  https://myrealty.am/en/2-bedroom/apartment-for...  
1  https://myrealty.am/en/3-bedroom/apartment-for...  
2  https://myrealty.am/en/3-bedroom/apartment-for...  
3  https://myrealty.am/en/3-bedroom/apartment-for...  
4  https://myrealty.am/en/3-bedroom/apartment-for...  

[5 rows x 24 columns]

In [2]:
df.Price.unique()

array(['600', '950', '890', '1300', '421', '3000', '1000', '400', '500',
       '550', '700', '330', '2500', '390', '450', '842', '463', '650',
       '1500', '316', '337', '520', '473', '800', '900', '1200', '2000',
       '1250', '850', '368', '420', '2300', '2400', '1400', '1900',
       '1600', '412', '2700', '780', '736', '350', '750', '5200', '1700',
       '432', '1100', '526', '2200', '1800', '300', '360', '2800', '430',
       '505', '358', '5000', '3500', '1850', '1894', '288', '618', '580',
       '670', '515', '370', '631', '980', '4000', '525', '320', '820',
       '530', '379', '2600', '930', '309', '480', '442', '381', '457',
       '380', '144', '572', '324', '540', '440', '415', 'on request',
       '304', '609', '223', '310', '720', '570', '1450', '690', '298',
       '947', '453', '990', '4500', '630', '329', '484', '699', '508',
       '1066', '730', '2345', '2900', '1595', '490', '884', '870', '2100',
       '721', '250', '476', '660', '590', '1350', '319', '290000

In [28]:
df['on_request'] = np.where(df['Price']== 'on request', 1, 0)
df.loc[df['Price'] == 'on request','Price'] = np.nan
df['Price/sqm'] = np.nan
df['Error'] = 0
df['Floors'] = np.nan
df['Listing_type'] = 'for rent'
df['Property_type'] = 'apartment'
df['Platform_name'] = pd.Series(random.choices(['myrealty.am','bars.am'],
                                                     weights=[1, 1], k=len(df)))
df.head()

ID                                  Location   Region  District  \
0  84218                Yerevan, Center, Saryan St  Yerevan    Center   
1  84217           Yerevan, Center, Sayat-Nova Ave  Yerevan    Center   
2  84181               Yerevan, Center, Amiryan St  Yerevan    Center   
3  84177           Yerevan, Center, Sayat-Nova Ave  Yerevan    Center   
4  84167  Yerevan, Arabkir, Baghramyan av(Arabkir)  Yerevan   Arabkir   

                    Street Price   Views  Area  Room  Floor  ...  \
0                Saryan St   600  2929.0    75     2      9  ...   
1           Sayat-Nova Ave   950  3036.0   103     3      7  ...   
2               Amiryan St   890  2694.0    75     3      9  ...   
3           Sayat-Nova Ave   950  2653.0   103     3      7  ...   
4   Baghramyan av(Arabkir)  1300  3009.0   120     3      4  ...   

                                          Facilities  \
0  ['Heating', 'Internet', 'Hot water', 'Electric...   
1  ['Heating', 'Internet', 'Hot water', 'Sewerage...   
2  ['Heating', 'Internet', 'Hot water', 'Electric...   
3  ['Heating', 'Internet', 'Hot water', 'Electric...   
4  ['Heating', 'Internet', 'Hot water', 'Sewerage...   

                                     Additional Info  \
0  ['Furniture', 'Equipment', 'Euro windows', 'Ti...   
1  ['Furniture', 'Equipment', 'Euro windows', 'Ir...   
2  ['Furniture', 'Equipment', 'Euro windows', 'Ti...   
3  ['Furniture', 'Equipment', 'Euro windows', 'Ti...   
4  ['Furniture', 'Equipment', 'Euro windows', 'Ir...   

                                                 url  on_request Price/sqm  \
0  https://myrealty.am/en/2-bedroom/apartment-for...           0       NaN   
1  https://myrealty.am/en/3-bedroom/apartment-for...           0       NaN   
2  https://myrealty.am/en/3-bedroom/apartment-for...           0       NaN   
3  https://myrealty.am/en/3-bedroom/apartment-for...           0       NaN   
4  https://myrealty.am/en/3-bedroom/apartment-for...           0       NaN   

  Error Floors Listing_type  Property_type  Platform_name  
0     0    NaN     for rent      apartment        bars.am  
1     0    NaN     for rent      apartment    myrealty.am  
2     0    NaN     for rent      apartment        bars.am  
3     0    NaN     for rent      apartment    myrealty.am  
4     0    NaN     for rent      apartment    myrealty.am  

[5 rows x 31 columns]

In [29]:
df['Price'] = df['Price'].apply(lambda x: float(x))
df.Price.quantile(0.999) #for threshold

32360.000000021955

In [30]:
df.loc[df['Price'] > 32360, 'Error'] = 1

In [6]:
df.Area.unique()

array([  75,  103,  120,   74,  130,   93,   55,   60,   65,   90,   48,
         78,   32,  100,   35,   85,  131,   67,  200,  210,   68,   57,
         53,   73,  180,   50,   41,   91,  170,  107,   80,   45,  105,
         83,  121,   95,   46,   98,   86,   43,   70,   97,   52,   92,
         37,   47,   72,  110,  199,   30,  185,  235,   96,   62,   64,
        250,  143,  150,  135,   89,   54,   40,   76,   58,  175,   44,
        140,   82,  160,  124,   81,   63,  125,  133,  309,   42,  270,
        145,  280,  240,   39,   84,  101,  117,   49,  165,  114,  163,
         77,  230,  207,   61,   94,  136,  182,  113,  108,   56,  171,
        154,  138,   79,  157,   66,  122,   36,  128,  159,  142,   51,
         59,  137,  126,   71,  115,  106,  300,   88,  169,  118,   31,
        127,  148,  134,  116,  102,  220,  215,   87,  111,  162,  129,
         38,  219,   33,  260,  151,   34,  350,  112,  360,  164,  190,
        191,  181,   99,  158,  132,   69,  104,  1

In [31]:
df.loc[df['Area'] < 20 , 'Error'] = 1

In [8]:
df.Views.describe()

count     5394.000000
mean      3441.154060
std       2353.303471
min         31.000000
25%       2106.000000
50%       2970.000000
75%       4973.250000
max      59564.000000
Name: Views, dtype: float64

In [9]:
df.Room.unique()

array([2, 3, 4, 1, 5, 6, 7])

In [10]:
df.Floor.unique()

array([ 9,  7,  4,  3,  2,  8, 11, 12,  5,  6,  1, 17, 13, 14, 10, 15, 16,
       20, 18,  0, 19])

In [32]:
df.loc[df['Floor'] == 0, 'Error'] = 1

In [12]:
df.Storeys.unique()

array([10, 11, 15, 16,  6,  5, 14, 12,  9,  8,  3, 17,  4, 13, 23, 18, 21,
       22, 20,  7, 19,  2,  1, 24, 25])

In [33]:
df.loc[df['Storeys'] == 1, 'Error' ] = 1

In [14]:
df.Bathrooms.unique()

array([1, 2, 3, 5, 4])

In [15]:
df.BuildType.unique()

array(['Panel', 'Monolit', 'Stone', 'Other'], dtype=object)

In [16]:
df.CeilingHeight.unique()

array([2.8, 3.2, 3. , 2.6, 3.8, 0. , 5. ])

In [34]:
df.loc[df['CeilingHeight'] == 0 , 'Error' ] = 1

In [18]:
df.Condition.unique()

array(['Good', 'Newly repaired'], dtype=object)

In [19]:
df.Latitude.describe()

count    5395.000000
mean       40.188879
std         0.109069
min        38.242697
25%        40.179601
50%        40.183333
75%        40.189950
max        44.521235
Name: Latitude, dtype: float64

In [20]:
df.Longitude.describe()

count    5395.000000
mean       44.441933
std         2.889293
min       -85.766224
25%        44.507282
50%        44.513076
75%        44.517895
max        46.403877
Name: Longitude, dtype: float64

In [35]:
df.loc[df.Longitude < 40 , 'Error' ] = 1

In [36]:
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace("]", ""))
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace("[", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace("]", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace("[", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace("'", ""))
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace("'", ""))
df['Additional Info'] = df['Additional Info'].apply(lambda x: x.replace(" ", ""))
df['Facilities'] = df['Facilities'].apply(lambda x: x.replace(" ", ""))
df1 = pd.DataFrame(df['Facilities'].str.get_dummies(sep=','))
df2 = pd.DataFrame(df['Additional Info'].str.get_dummies(sep=','))
info = pd.concat([df1, df2], axis=1)
apt_rent = pd.concat([df, info], axis=1)
apt_rent.head()

ID                                  Location   Region  District  \
0  84218                Yerevan, Center, Saryan St  Yerevan    Center   
1  84217           Yerevan, Center, Sayat-Nova Ave  Yerevan    Center   
2  84181               Yerevan, Center, Amiryan St  Yerevan    Center   
3  84177           Yerevan, Center, Sayat-Nova Ave  Yerevan    Center   
4  84167  Yerevan, Arabkir, Baghramyan av(Arabkir)  Yerevan   Arabkir   

                    Street   Price   Views  Area  Room  Floor  ...  Parquet  \
0                Saryan St   600.0  2929.0    75     2      9  ...        0   
1           Sayat-Nova Ave   950.0  3036.0   103     3      7  ...        1   
2               Amiryan St   890.0  2694.0    75     3      9  ...        0   
3           Sayat-Nova Ave   950.0  2653.0   103     3      7  ...        0   
4   Baghramyan av(Arabkir)  1300.0  3009.0   120     3      4  ...        0   

   Playground Roadside  Sauna Securitysystem Storageroom Sunny Swimmingpool  \
0           1        1      0              0           0     1            0   
1           1        1      0              1           0     1            0   
2           0        0      0              0           0     1            0   
3           1        1      0              1           0     1            0   
4           1        1      0              1           0     1            0   

   Tile  View  
0     1     1  
1     1     0  
2     1     1  
3     1     1  
4     1     1  

[5 rows x 78 columns]

In [24]:
apt_rent.columns

Index(['ID', 'Location', 'Region', 'District', 'Street', 'Price', 'Views',
       'Area', 'Room', 'Floor', 'Storeys', 'Bathrooms', 'BuildType',
       'CeilingHeight', 'Condition', 'Date Added', 'Date Edited',
       'Date Scraped', 'Latitude', 'Longitude', 'Address', 'Facilities',
       'Additional Info', 'url', 'on_request', 'Price/sqm', 'Error',
       'Air-conditioner', 'Canalization', 'Centralheating', 'Electricity',
       'Gas', 'Heating', 'Hotwater', 'Internet', 'Irrigation', 'Sewerage',
       'Water', 'water24/7', 'Attic', 'Balcony', 'Basement', 'Bilateral',
       'Buildingexistence', 'Closetothebusstation', 'Elevator', 'Equipment',
       'Eurowindows', 'Fence', 'Fireplace', 'Furniture', 'Garage', 'Gate',
       'Grating', 'Gym', 'Heatedfloor', 'Heater', 'Highfirstfloor', 'Irondoor',
       'Laminateflooring', 'Loggia', 'Openbalcony', 'Park', 'Parking',
       'Parquet', 'Playground', 'Roadside', 'Sauna', 'Securitysystem',
       'Storageroom', 'Sunny', 'Swimmingpool', 'Ti

In [37]:
apt_rent.to_csv('apt_rent_filtered.csv', index = False)